### ISSUE TITLE
Geolocation is updated once every 5 seconds even when moving very fast

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#106]
While this is handy (object list does not change that often), the code does not imply that interval. Investigate and make predictable.

**Comment by pkoby** [comment]
I'll comment in here because I don't know that it's a separate issue.

I've noticed a few quirks with the location handling in this app compared to others.

1. If you turn off "Google Location Accuracy" (it's called that in Android 9 at least) which would allow Google to use wifi or cellular networks to help location, Every Door pops up to ask to turn it on every time you open the app. Location works fine without it in the app, so it's not a necessity. Other apps I have (aside from Google Maps) do not ask for this feature.
2. As mentioned, it seem to only refresh location every so often, despite expectations.
3. Most notably, I've noticed that it seems like this app heavily increases my battery usage even if I don't use it very long. From some not-very-scientific testing, I noticed that Google Play Services is what uses most of that extra battery, probably stemming from point 1 above. After I noticed that, I tried using Every Door just as much, but force-stopping the app after use. Battery was fine.

So something about how you handle location seems to be polling Google Play Services location more than it should, and maybe even when the app is closed (not sure about this). If it helps, I checked Developer Options in Android, and in the Standby Apps section, Every Door had the "app standby state: Frequent", whereas similar apps are Rare. Not really sure it that is relevant, though.

**Comment by Zverik** [comment]
The issue was gone after upgrading to Android 12 :/

**Comment by iandees** [comment]
Is the resolution that the app is updating as often as possible? I'm noticing that the dot updates very infrequently and that makes it hard to map while a passenger in a car or even while walking.

Let me know if I should open a new ticket.
