### ISSUE TITLE
[Proposal] Filter by check_date

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#12]
I want to be able to filter out amenities that I or others have already checked so only things that have not been checked in a while will be shown

**Comment by Zverik** [comment]
It's not hard to make such a filter, but I'm worried it would hurt the usability. E.g. you might forget the filter is on, and find just one shop missing among many un-surveyed. You'll add it and never find out that it was present, but surveyed by somebody testing the editor.

Usually you don't see more than half a dozen shops around you, so it won't hurt if you see surveyed shops as well in the list. Filtering by floor and address is more important, since you don't see shops on another floor.

**Comment by mfbehrens99** [comment]
If you say it is easy to implement I would suggest adding it in and see if it is hurting the usability. Most users won't ever press the button.

However, I think the pending uploads should still be displayed or else it would be very difficult to undo a falsely pressed check.

In general, I think this feature could benefit especially in big malls.

**Comment by Zverik** [comment]
Done in 0.1.2.
