### ISSUE TITLE
[Proposal] Add team mode

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#14]
I really like the team mode from street complete since it works offline and makes working in a team much easier.

Easiest would be to just copy the concept. Essencially it just takes the OSM id modulo team size and checks if the result equals you team member index:

`quest.stableId % teamSize == indexInTeam.toLong()`

Full code can be found here:
https://github.com/streetcomplete/StreetComplete/blob/e34f3b5163d4c443c6436fddb531c1116c0529a7/app/src/main/java/de/westnordost/streetcomplete/data/visiblequests/TeamModeQuestFilter.kt

Edit: Could even be improved by hashing the OSM id before the modulo to compromise for potential id biases, but this is just an idea

**Comment by Zverik** [comment]
Great idea for StreetComplete (or HOT tasking manager), but I don't see how it can be applied to this editor. It's like adding a team mode to iD. The best I could think of is to ask team members to re-download their areas once every half an hour.

Also, since 0.1.1 uploads are actually merged in, so you could collect e.g. a phone and a website, another person could add opening hours and wheelchair accessibility, and there'll be no conflicts and all tags will be merged in regardless of the uploading order.

To me, surveying an amenity twice is better than none at all. It's not like it would take a lot of time :)

**Comment by mfbehrens99** [comment]
I am not sure if we are talking about the same thing. I think every door is rather like street complete than iD. With both apps you are out in the field and collect data. I usually go out and do street complete with a friend. The number of mappers is two, one person picks A and the other B. Then we go for a hike and both persons only have to do half of the work and don't create any conflicts or do exactly the same work.

**Comment by Zverik** [comment]
Well, each interaction with StreetComplete change 1-2 tags on a single object, making "horizontal" teams possible, when a single object can be visited by multiple people. Contrary to that, Every Door makes you fill as much info as possible for each object.

Hence the split between team members should be not logical (by "quests"), but physical: which POI does one collect and which don't. Thing is, this is solved outside of the app: e.g. by splitting the area in parts and assigning them to people. Randomizing would make everybody visit the same shops, and there'll be much confusion over what to map and what to skip.

To me, the possible benefit of introducing teams is negligible. To do it properly, I would need to set up a great new chunk of functionality: for planning mapping events, communicating between team members, keeping a leaderboard etc etc. I do not want that, because that would detract from the main functionality: editing.
