### ISSUE TITLE
Support Tag2Link rules to get URLs for a tag

### ISSUE THREAD

**Issue by pyrog** [Zverik/every_door#178]
See [Tag2Link](https://josm.openstreetmap.de/wiki/Help/Action/Tag2Link) and JOSM ticket [#21988](https://josm.openstreetmap.de/ticket/21988).

Also an appropriate SPARQL query could return a format constraint as a regular expression.
See [SIRET number ](https://www.wikidata.org/wiki/Property:P3215#P2302) on wikidata.

See also https://github.com/Zverik/every_door/issues/140#issuecomment-1125789680.

**Comment by Zverik** [comment]
No. There will be no wikidata, sparql or any other obscure things in this editor. The editor is for collecting data, not for in-depth maintenance of mapped objects. The less fields the better.

**Comment by pyrog** [comment]
Could we discuss this point ?

> The editor is for collecting data,
👍 

One could check data on the field, like Facebook or official identifiers like SIRET.

SPARQL is difficult to learn but that's not the point.

- You could get a simple json from [this project](https://github.com/JOSM/tag2link/blob/master/index.json).
- Tag2Link is a **universal** way to add links, open them (and check identifiers values).
It is used at least by JOSM and Osmose Q&A.

> The less fields the better.
👍 

One could use the future profile system to display only what he need.

**Comment by Zverik** [comment]
Thing is, this editor is intended to be used in the field. You tap a button, fill as much info as possible in a short timeframe, and move to the next amenity. This proposal introduces a dependency on a web service (of which the app has just two: imagery and OSM, both optional when surveying). I do not want that, since it rises a question, why package all the presets and imagery lists when I could download them when needed.

Also this is a working plugin for JOSM, so people who are interested (and I believe there are less than 100 of them in the world) could use it to mass-add needed information.

**Comment by pyrog** [comment]
> This proposal introduces a dependency on a web service

No if rules are packaged with the app: a script run SPARQL queries and store data in a json file.
The script could be run manually or run automatically by continuous integration workflows.

(JOSM do SPARQL queries in the past, now it use webjar. A [script](https://github.com/JOSM/tag2link/blob/master/build.js) run manually "build" the index.json file stored in this webjar). 

But if **Every Door** will have **custom presets** (see #119) then tag2link is not mandatory 😃
