### ISSUE TITLE
Allow house numbers without streets

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#190]
Turns out many people like to add these.
But make it after a big red warning or something.

**Comment by bgo-eiu** [comment]
I would say the warning should only show in some countries. In Japan it is common for addresses to have no street name, and instead they have a block number.

I will also note, since this was documented incorrectly on the wiki until yesterday, there are two different ways to tag a block in an address. addr:block_number is used in Japan for blocks that actually have numbers, whereas addr:block is used in countries like India where blocks can have full names rather than numbers.

**Comment by Binnette** [comment]
I just found this bug too. If you set only the housenumber and save changes, then the housenumber will not be saved. 

- Either we allow to set only the housenumber
- Or we can put a warning message somewhere that tell the user that he "forget/omit" the street.

Have a nice day.

**Comment by Zverik** [comment]
Done in 0.4.
