### ISSUE TITLE
[Feature Request] Display the date of the last modification of the object 

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#20]
To delete a POI, you need to make sure that it really does not exist. In a large building, this can be difficult. A hint in this may be the date of the last edit of the object.

It can be displayed in an extended list of tags in order to make decisions based on it last and not make unnecessary requests.

**Comment by Zverik** [comment]
This is an editor specifically for on-the-premise surveying. You have a floor filter for filtering out venues on different floors. So to make sure something does not exist, you just look around :)

Using dates from OSM metadata won't help you with anything, since people often add amenities remotely. And for `check_date`, that's what checkmarks are for.
