### ISSUE TITLE
When choosing the last preset, use tags from the last added object

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#213]
To speed up adding multiple e.g. benches of the same kind.

**Comment by BudgieInWA** [comment]
You should be able to choose a fresh empty feature, or to use (transferable) tags from,
1. the last feature of this type that you added,
2. any nearby (or loaded) features of this type.

**Comment by Zverik** [comment]
Done in 0.5. Did not copy tags from features around, because you never know what's there.

**Comment by gdabski** [comment]
Ugh, I almost filed a bug regarding this behaviour assuming it wasn't intentional. I'll keep an eye on this, but also there's also a question. Is the autofill with data of the last feature of this type performed:
* only when adding several points of same type in a row?
* with data of previously added point of same type, regardless when?
* with data of previously edited point of same type, regardless when?

One more note: for most categories, like shops, this feature isn't really useful. Maybe it should be limited to selected ones?

**Comment by ygra** [comment]
It would be nice if those remembered tags would also be shown when selecting an object type. The way it is right now it confused me as well that some of them retain what I've entered before and some do not.

**Comment by mnalis** [comment]
Maybe make a selection (slightly) different color if it was autofilled automatically from previous object (as opposed if it was present on the object itself or manually set by the user on this object)?
