### ISSUE TITLE
[Request] Keep zoom levels persistent across modes

### ISSUE THREAD

**Issue by pkoby** [Zverik/every_door#230]
I would like to request that the zoom level has a more persistent state. Currently, I think Micromapping and POI modes keep the same zoom level if you switch between them, but going to Entrance mode zooms out. Returning to the other modes from Entrance mode then zooms them out as well.

I would like it if either:
1. the zoom level stays the same in every map page regardless of how you switch to it (including fine-tuning position)
2. each mode keeps its zoom level when you go back to it. So if I'm at z19 in Micromapping, z17 in POI, going back to Micromapping would be back to z19.

**Comment by BudgieInWA** [comment]
I had the same annoyance. Especially when lining up the cursor, pressing "+" and having a new map appear on top, with a different zoom (annoying when the "add item" map is zoomed further out than the previous map).

My expectation is that there is one map view, which changes sizes to accommodate the different accompanying UI, instead of having each screen come with its own map. This might require panning the map when the shape changes, to keep the cursor positioned appropriately within the viewport (or in the center). Having smooth panning transitions when switching between modes, or when tapping on a busy area in micromapping mode, etc., would make it much easier to keep oriented as one moves through the app.

This is how OSMAnd, Organic Maps and Google Maps feel: there is a single map, with additional UI coming in from the top or bottom as needed. Google Maps does a good job of framing the current subject on the map when the screen changes, but I am often annoyed when it zooms into something unnecessarily, so I would err on the side of "let the user position the map" and only reposition when its definitely helpful (e.g. when the changing shape would cause the subject to move out of frame).

**Comment by waldyrious** [comment]
Adding another voice for not changing the zoom level when changing modes, especially when adding a new item to the map. This is quite disconcerting in POI mode, where not only the zoom changes, but the map also moves because the bottom panel listing existing POIs disappears from the bottom when one clicks the <kbd>+</kbd> button:

https://user-images.githubusercontent.com/478237/184311999-204eb9b3-b1a4-4985-9e8e-850fd9991e79.mp4

(The sudden panning of the map is related to #136.)

**Comment by Zverik** [comment]
Done in 2.1.
