### ISSUE TITLE
Visual editor for direction and camera:direction fields

### ISSUE THREAD

**Issue by cascafico** [Zverik/every_door#327]
I often use the app to add surveillance cameras. In general, to map objects featuring angle attribute is rather difficult without overlayed map orientation info as a reference.

**Comment by Zverik** [comment]
I would not clutter the interface just for a single use-case, but this gives me an idea for a better editor for directions. Sorry, I'm hijacking this issue for that :)

**Comment by Zverik** [comment]
Done in 3.0.

**Comment by mnalis** [comment]
Would it make sense to allow direction choosing on `information=guidepost` ?

**Comment by Zverik** [comment]
This is about [the preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/tourism/information/guidepost.json), not the editor. And as I see on [the wiki page](https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost), direction info on a guidepost is a little complicated, since arrows can point in all directions.

**Comment by ygra** [comment]
The most robust way of adding arrow directions on guideposts is IMO a destination_sign relation, where the arrow direction comes for free from the ways that it leads to (plus, it offers data consumers way more information than just a direction in terms of how to follow a guidepost's directions).
