### ISSUE TITLE
Ask for confirmation when canceling notes which has text entered.

### ISSUE THREAD

**Issue by mnalis** [Zverik/every_door#363]
When commenting on a note, one might click `CANCEL` instead of `OK`, and all the text they've entered would disappear.
That is especially likely as `CANCEL` and `OK` buttons are close together.

It would be nice if `CANCEL` button would ask for confirmation if any text was entered in the comment field (similarly how  `CLOSE` button asks). Of course if no text was entered, note window could be dismissed without any confirmation, as there is not a danger of data loss.

**Comment by Zverik** [comment]
Okay, but since I promised translators not to add any more strings, I've marked this for 1.x or 2.0.

**Comment by Zverik** [comment]
Done in 2.0.

**Comment by danieldegroot2** [comment]
@mnalis @Zverik I suggest to modify `notesCancelMessage` and `editorCloseMessage` to respectively
> [Cancel your OSM note? / Close the editor?] You will lose your unsaved changes.

This will make the text consistent and keep it comprehensive for users why -and where- they are being shown this message.
You may choose to add the second part on a new line, or as a seperate translation so it doesn't have to be translated twice.

Otherwise, I would suggest for `editorCloseMessage` to keep the previous translation or change it to
> Discard changes?

Recently, the suggestion was accepted to change it to "Discard changes without saving?". Noteably, "Discard" is the same as "without saving". I would understand this if it was "Discard changes without saving as a draft?", but this takes longer to read.
