### ISSUE TITLE
Default currency per country

### ISSUE THREAD

**Issue by j9d3it** [Zverik/every_door#446]
Hello, when I'm editing in my country I have to choose the currency from a huge list and it's a pain. Not sure about other countries but mine only uses one and it's definitely not USD, EUR or RUB which are the ones that show up first if I'm adding for example a vending machine.

I'm wondering if the currencies can just be automatically determined from the country the POI is being added in, and have it be pre-selected when you add something. That would save a lot of time.

Also the list is not in alphabetical order when I open it up which makes it hard to find the currency. I have to open up the keyboard every time and type it in to find it. I think the list is sorted by popularity which works for most things but not for currencies.

**Comment by Zverik** [comment]
The list should be sorted according to the currency already present on POI. Is that not the case for you? Could you plz share the location?

**Comment by j9d3it** [comment]
[Here is the object.](https://www.openstreetmap.org/node/10038478658) 

JPY appears when I select it, yes, but when I add another vending machine or something in a new session I have to search for it. If it's an existing POI it works fine, but if I'm adding a new one JPY does not show up unless I go into the menu to select it from the big list of currencies. Since I'm in Japan, I'd expect currency:JPY to be the default.

![here's a screenshot of the node as it appears in app.](https://user-images.githubusercontent.com/26203575/191511557-144ba55e-afdc-404c-a1b5-cc8683aa233d.png)

**Comment by mnalis** [comment]
While I do not have much experience with Japan specifically, I do not see much point (and in fact, find it bad practice) to _explicitly_ map such _default_ currency. If the currency is default (e.g. `JPY` in Japan), it should not be mapped at all. 

Only **_if_** the amenity supports **_non-default_** currencies, should all of them be mapped (e.g. `JPY`+`USD`).

If you agree with this reasoning, it would kind of make you problem go away.

As an example why I find it bad behaviour: default currency in Croatia is currently `HRK`. Hopefully it is **not** mapped on amenities **only supporting default currency** (i.e. 99% of them), because we're soon to transition to Eurozone, which would require re-surveying all such locations, and checking if they support only new default (`HRK`+`EUR`) and re-map them all. And then, when transition period ends, all such locations would need to be resurveyed again, and checked if they support new default (only `EUR` or something else). Of course we would need to leave `note` tags too, to know if that location has actually been resurveyed according to newer law (and which one).

Besides all that, it does not add any new information which is not implied anyway, and it needlessly makes OSM **database bigger**, and it **wastes mapper time** (which could be better used elsewhere) - for **no advantage** at all.


Do we map every `highway=primary` with (default) `motorcar=yes`? No, we would only map non-default behaviour there (e.g. if some primary road did not support motorcars!)
In the same manner, I think we should not map default currency on amenities - only when the currencies actually differ from the default for that country.

**Comment by j9d3it** [comment]
Aha thank you for the explanation, that makes sense. So I can just not select JPY since it's implied for the country I'm in. Thank you!
