### ISSUE TITLE
Disable the ability to add buildings as nodes

### ISSUE THREAD

**Issue by Mannivu** [Zverik/every_door#456]
I understand that Every Door is great for new users, but the ability to add a node and tagging it with `building=yes` creates quite a lot of problems because new users don't know that buildings can be added as nodes and if a user adds a lot of building, other users have to fix every building (and the imagery is not always up to date).

**Comment by deevroman** [comment]
If you disable this feature, users will not be able to add new addresses for buildings that are not on the map. 
If you allow users to add only addresses, then... why not allow them to be labeled as buildings?

By the way, please note that the function of adding new addresses is expected in StreetComplete. If she's going to be there, it's unclear why she can't be in EveryDoor https://github.com/streetcomplete/StreetComplete/releases/tag/v48.0-alpha1

**Comment by Mannivu** [comment]
I see your point and I understand it, but I still think that adding buildings just as nodes is impractical for the final user of OSM. Maybe the app should suggest the user to edit the building or add a "fix me" stating that the building the user has just added is on a node.

**Comment by mnalis** [comment]
> I see your point and I understand it, but I still think that adding buildings just as nodes is impractical for the final user of OSM.

As a final data consumer, I'd much rather if mappers have mapped **many** the addresses as **nodes** with `building=yes`, then if only a **few** addresses are mapped because only a few building polygons were drawn. While it is possible to use some mobile editors (like Vespucci) to draw building polygons, it is **_much more work_** especially on mobile screens (and thus _much less likely to happen_ often, if at all).

> Maybe the app should suggest the user to edit the building or add a "fix me" stating that the building the user has just added is on a node

How would that help? Desktop mapper who comes afterwards would still have to convert node to polygon for that building, and then they'd have to remove extra `fixme` tags. It is just extra work for them.

It seems to me that adding an building as a node is preferable to not adding a building at all because it is too complex (which is only realistic outcome if bulding-as-a-node functionality would be removed). So I'd vote for this functionality to stay. 
First priority should be map for usability (e.g. having address nodes at all!), and nicer geometry (e.g. buildings as polygons) is just a nice eye candy that comes afterwards (_if_ there is time).

If you much prefer [buildings as polygons](https://wiki.openstreetmap.org/wiki/Key:building#How_to_map), there are two basic ways to handle that:

- **proactive** - draw all buildings as polygons in your area from aerial background. When all buildings are drawn as polygons, EveryDoor and StreetComplete etc. users won't have to add them as nodes, but will just update those polygons with extra data, so the problem of buildings-as-nodes is gone.
- **reactive** - periodically search for buildings mapped as nodes (e.g. with this [overpass query](http://overpass-turbo.eu/s/1mrB)) and convert them to nicer-looking polygons in desktop editor like iD or JOSM using aerial/satellite imagery (where such jobs is _much easier and faster_ to do, especially with JOSM's `building_tools` plugin)

**Comment by Zverik** [comment]
Thanks for the discussion guys! My position is as follows:

1. Every Door is not for novice editors, it's an equivalent of JOSM, which needs some learning.
2. Adding building information in the field is super important, while drawing geometry on a phone is hard and slow.
3. Building outlines are overrated. Seriously, for most if not all practical uses you need only attributes, not geometry.
4. And the wiki allows building tags on nodes, making the ED mapping valid.
