### ISSUE TITLE
Add the option to mark the building as abandoned

### ISSUE THREAD

**Issue by deevroman** [Zverik/every_door#502]
Now you can only mark it as Non-existent. In practice, buildings often stay in place for a long time and serve as a landmark, but people stop caring for them.

**Comment by mnalis** [comment]
I think that answer is already there, under `Other` => `Abandoned`  (or `Ruined`), or is that not what you are asking for?

**Comment by deevroman** [comment]
`Other`? Where is it located?

And in fact, I propose another button in addition to the already existing Does Not Exist

<details>
<summary>Details</summary>

![-212171_temp](https://user-images.githubusercontent.com/25708359/205726287-1c7b95a1-1148-4101-9748-c8b9151fc173.jpg)

</details>

**Comment by mnalis** [comment]
In that picture of yours, under `Building` row, you can click `...` and choose `ruins`, if that helps?

**Comment by deevroman** [comment]
Hmm, an interesting question is which tag to use. I initially thought about the [abandoned=yes](https://wiki.openstreetmap.org/wiki/Tag:abandoned%3Dyes) tag. But it turns out that there is a similar tag [disused=yes](https://wiki.openstreetmap.org/wiki/Tag:disused%3Dyes).

[buildings=ruins](https://wiki.openstreetmap.org/wiki/Tag:building%3Druins) is also suitable, however, using it we lose the former purpose of the building.

**Comment by mnalis** [comment]
> [buildings=ruins](https://wiki.openstreetmap.org/wiki/Tag:building%3Druins) is also suitable, however, using it we lose the former purpose of the building.

That is true. Do note that instead of adding tags like `abandoned=yes`,  it would be better to use [lifecycle prefix](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix), (e.g. mark it as `abandoned:building=house` or whatever). 

In EveryDoor for building, as far as I know, you can do that only in manual tag editor (icon in the upper-right part of titlebar which says current building type); there are currently no buttons to set that more easily.

**Comment by deevroman** [comment]
But `abandoned:building` key is deprecated https://wiki.openstreetmap.org/wiki/Key:abandoned:building

**Comment by mnalis** [comment]
> But abandoned:building key is deprecated https://wiki.openstreetmap.org/wiki/Key:abandoned:building

Interesting. Somebody seems to have changed wiki definition last year based only on short comment by one other user on talk page, without any larger discussion.  Previous revision looked like [this](https://wiki.openstreetmap.org/w/index.php?title=Key:abandoned:building&direction=prev&oldid=2172878) and defined `abandoned:building` as _"A building which has been abandoned and is no longer functional due to serious damage to roof or walls, but which is still visible in the landscape"_.

They seem to have changed `abandoned:building=*` to `building=ruins` (and thus incurred loss of data precision, as you note!) with reasoning that they did it because _"it is still a building, even when it doesn't have a roof."_

That however disagrees with common [wikipedia definition of the building](https://en.wikipedia.org/wiki/Building) as _"enclosed structure with a **roof** and walls standing more or less permanently in one place"_ (emphasis mine). So, in my opinion, such change was wrong (and contrary to common mapping practice, especially as [building=ruins](https://wiki.openstreetmap.org/wiki/Tag:building=ruins) has its own set of issues/confusion. 

Thanks for bringing it to my attention though, I'll comment further on those wiki pages and attempt to rectify the situation. I do agree with adding `disused=yes` to `building=house` which is just disused (because it is, as the claim goes, _"still a building"_).
