### ISSUE TITLE
Broken Default payment cards option

### ISSUE THREAD

**Issue by kudlav** [Zverik/every_door#530]
Hi,
I would like to set the default payment cards options, but this settings has no effect.

1. Set the _Default payment cards_ to _cards; contactless_
2. Go to poi (https://www.openstreetmap.org/node/365585365)
3. Select _accepted_ next to the card icon
4. Completely different payment tags are added (see the screenshot)
![Screenshot_20230123-222813](https://user-images.githubusercontent.com/11516259/214155240-2b0c4329-759b-44dd-b567-bd2461cf5cbe.png)

SM-A405FN
Android 11
App 3.0.0 via F-Droid

**Comment by Zverik** [comment]
I've investigated this, and the logic is more complex. The setting is called _default_ payment values, that is, which are used in case there is no other data. If shops around have payment options for cards set, these values are used instead. So in your case, at least a third of shops had these five tags set. Probably some other mapper used that for the default :)

**Comment by kudlav** [comment]
What?! This is dangerous and unpredictable behaviour. I have contactless Visa. When I visit a shop and I am able to pay by that, then I want to set my preconfigured tags.
You can't add tags from another shop. Just because someone else was able to pay contactless in different shop, it doesn't mean it's possible in the shop next to it.

**Comment by mnalis** [comment]
I agree, it absolutely **should not be done behind mappers back**. I've probably mismapped many shops around here because I was not expecting such trickery (e.g. while Visa/Visa Electron/Mastercard are universally accepted here, only some shops accept American Express and/or Diners - so if the tags added silently depending on nearby shops, the payment tags will be added randomly! I'll probably now have to find all payment tags I've added with EveryDoor and replace them with`payment:cards=yes` )

Can we please reopen this issue?

**Comment by mnalis** [comment]
What I'd suggest is one of those which avoid that issue of ***"unexpected and unnoticed mismapping"*** which is a big deal (from the least preferred at the top, to the most preferred at the bottom):
- get rid of that `Default Payment Cards` preference, and tag only `payment:cards=yes` 
  **Advantage:** the mapper will always be fast and correct, no preference to miss by new users, easiest to implement
  **Disadvantage:** the detail is missing, workload of determining actual cards used is shifted from mapper to data consumers (which then need to scan nearby stores to determine what cards that might be or do other educated guesses), EveryDoor logic seems to be so mapper can add as many details as possible. 

- if user clicks that cards are accepted, tag only cards under `Default Payment Cards` in preferences
  **Advantage:** expected behaviour and user is aware of that
  **Disadvantage:** the actual cards might differ so it is on mapper to doublecheck, and to manually enter them if they differ

- do the lookup of nearby shops, and if the card payments result differ from user-specified `Default Payment Cards`, show a dialog showing `A selection vs. B selection` and ask user to select which one they want to use
  **Advantage:** expected behaviour, and in addition it tries to help the user (and if the premise that the neighborhood area is the same as user selected default actually holds, there is no extra clicks required of user) 
  **Disadvantage:** more work to implement, user is still on its own if neither of two offered choices apply

- when `card accepted` is selected, open a dialog asking the mapper to confirm all choices that apply (pre-filled only with `Default Payment Cards` preference, but typing in search window allows user to add extra cards). Alternative extra: remember last set of values user entered, and use that instead (and have a button to reset to `Default Payment Cards`).
  **Advantage:** expected behaviour, allows user to add all details easily, only one extra click in default case when information is correct.
  **Disadvantage:** user need one extra click in default case, most work to implement

**Comment by Zverik** [comment]
Yeah, I agree the current way is not ideal. I've created #530 to rework this in the future (idk when exactly). Thanks for suggestions! I'm looking into removing the setting, and adding a button to specify payment methods in the form itself. But in that case I don't yet know what to save, or maybe to set the defaults uniform for everybody with an option to edit for individual objects.
