### ISSUE TITLE
EveryDoor assumes all plaques are to be snapped to a building

### ISSUE THREAD

**Issue by ivanbranco** [Zverik/every_door#565]
If you add a memorial=plaque, EveryDoor automatically adds a _"fixme=Please merge me into a nearby building"_, but this isn't always the case, as can be seen in the Wiki page in the _"Examples"_ paragraph: https://wiki.openstreetmap.org/wiki/Tag:memorial=plaque

Also if you add it and save the element (without uploading) and you get back to the same element to add a new tag, there's no trace of the fixme, that appears only after the upload. Maybe could be a good idea to add it as you click the preset, so you can notice it and delete it if not relevant to the case.

**Comment by gdabski** [comment]
It's not that simple, because the fixme is only added when the app for some reason fails to snap the plaque to a building. The default is to snap to a nearby building outline, which misplaces the node if the plaque isn't in fact placed on a building wall.

By the way, I find the post-mounted plaque from Wiki a questionable example. To me it's rather an information board. But there are of course plaques mounted on walls (i.e. barriers), on the ground or on not-yet-mapped features.

**Comment by Zverik** [comment]
So how we can do this: first add a [support](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/support.json) field to the [plaque](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/historic/memorial/plaque.json) preset. And then Every Door can skip the snapping when the `support=post` tag is present.

Since it's common for plaques to be on buildings, I assume this would be the best option. And we need more plaques with the support tag set :)

**Comment by ivanbranco** [comment]
There are 1212 uses of support with memorial=plaque atm:



</head>

<body link="#0563C1" vlink="#954F72">


support|uses
-- | --
wall_mounted | 632
wall | 218
pole | 160
rock | 66
ground | 39
bench | 20
stone | 17
post | 13
pedestal | 12
tree | 12
fence | 9
guard_rail | 3
column | 3
board | 2
support | 1
pole_mounted | 1
billboard | 1
ground;flower bed | 1
posts | 1
pillar | 1



</body>

</html>

Most of them don't need to be merged to a wall, not =post only. =pole, rock, ground, tree, fence ecc. also.

Maybe the check could be something like this?: if support is missing or is =wall_mounted OR =wall, then look for a building for merge

**Comment by gdabski** [comment]
Also see #541 for a more general issue.

**Comment by Zverik** [comment]
Okay I've disabled snapping plaques until I do #541. After that I'll re-enable.
