### ISSUE TITLE
Missing tags and keys

### ISSUE THREAD

**Issue by j13m126** [Zverik/every_door#590]
It would be great if you could add these missing tags in a future release.

- [leisure=parklet](https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dparklet)
- [amenity=brothel](https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dbrothel)

- [centralkey](https://github.com/Zverik/every_door/issues/590#issue-1742597049) (for amenity=toilets)
- [changing_table:location](https://wiki.openstreetmap.org/wiki/Key%3Achanging_table) (when changing_table is set to yes)
- [indoor_seating](https://wiki.openstreetmap.org/wiki/Key%3Aindoor_seating) ()

- amenity=locker
- amenity=luggage_locker

Mapping with Every Door is a real pleasure, thank you! :)

**Comment by Zverik** [comment]
Went through the list, thank you for preparing it.

* parklets and brothels are technically supported, but you would need to add the presets to https://github.com/openstreetmap/id-tagging-schema (so that iD also supports these). Same for lockers.
* for centralkey, you need to add the field to the [toilets preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/toilets.json).
* same for indoor_seating, copy the outdoor_seating field and add it to [bars](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/bar.json) and other kinds of eateries.
* For changing table locations, again you would need to add the field and the add it to presets that have changing tables.

So yeah, I am sorry, but all this will be supported in Every Door after it's been accepted to the tagging presets. I'd be grateful if you did it :)
