### ISSUE TITLE
Opening hours for indoor playground cannot be set/edited

### ISSUE THREAD

**Issue by habi** [Zverik/every_door#593]
Visiting https://www.openstreetmap.org/way/46159225 I wanted to set/update `opening_hours`.
I haven't found a way to do this in the GUI, only in the raw tags editor, making it cumbersome to edit them (missing the nice editor).
![image](https://github.com/Zverik/every_door/assets/1651235/b91d9ee0-2413-4e49-8027-036c19c288d6)

**Comment by mnalis** [comment]
It seems to be because it is tagged with [leisure=playground](https://wiki.openstreetmap.org/wiki/Tag:leisure=playground). According to that wiki, it can have `opening_hours` (and it makes sense for `indoor=yes`), but id-tagging-schema does not seem to have that option, if I'm seeing correctly. 

So you could open [issue](https://github.com/openstreetmap/id-tagging-schema/issues)/PR there: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/leisure/playground/indoor.json

Alternatively, you could've clicked on that `Indoor Playground` title, and changed type to `Indoor Play Center` (with [leisure=indoor_play](https://wiki.openstreetmap.org/wiki/Tag:leisure=indoor_play) which looks like single-tag alternative tagging for that (and which does have `opening_hours`)

**Comment by habi** [comment]
Thanks for the input.
I think IDs tagging schema should allow for playgrounds with `opening_hours`, as many of them (mostly outdoor) have 'allowed times'.
I'll submit an issue with ID.
