### ISSUE TITLE
Background imagery disappears when zoomed in too much

### ISSUE THREAD

**Issue by Zaczero** [Zverik/every_door#599]
https://github.com/Zverik/every_door/assets/10835147/574f8899-22ab-45e1-963f-d886f5771ee8

This is very annoying when I want to position a newly added element.

**Comment by Zverik** [comment]
That happens when a satellite imagery layer is added to the [layer index](https://github.com/osmlab/editor-layer-index/) with maxZoom higher than it actually provides. I won't, and probably cannot, write a detection algorithm to fix that kind of a mistake.

Please check if the iD editor behaves similarly at that place with that imagery.

**Comment by Zaczero** [comment]
![image](https://github.com/Zverik/every_door/assets/10835147/abcd1585-0874-4079-8568-1bc497b7c712)

It does not, you can test it pretty much anywhere in Poland.
Screenshot taken from max iD zoom level: 24.

We are talking about this layer:
https://raw.githubusercontent.com/osmlab/editor-layer-index/3c493f8c7ed65b046b76351013cb69d31711b4dc/sources/europe/pl/Geoportal2Orthophotomap(aerialimage)_WMTS.geojson

**Comment by Zaczero** [comment]
I believe this issue has been closed a little too quickly

**Comment by Zaczero** [comment]
![image](https://github.com/Zverik/every_door/assets/10835147/bdc614c9-8a6b-4f4f-a2a8-328c195cdf2b)

This also happens with bing, it's not geoportal-specific issue it seems.

**Comment by gdabski** [comment]
AFAIK this only happens with the Geoportal WMTS and not with the WMS imagery. Not sure if it's exactly true, but I always attributed it to a purported feature of WMTS that it responds with an error (or with blank tiles?) if the request has a zoom level beyond a certain threshold. You can deduce from [getCapabilties](https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&request=getcapabilities) that there seem to be different limits on zoom levels depending on projection, maybe this is where a difference between iD and EveryDoor exists?

Also note that the grey tiles for Bing have no-photo watermarks across them while the Geoportal ones don't, which shows that it's not the app that is the origin of the situation.

**Comment by Zaczero** [comment]
> Also note that the grey tiles for Bing have no-photo watermarks

This is the result of zooming in too much, when zooming out on bing it works as usual. Geoportal displays white tiles, bing displays this. It's just a different way of handling such too much zoom cases.

**Comment by gdabski** [comment]
> This is the result of zooming in too much.

I understood you were implying the grey background is an artifact coming from the app, sorry.

>  Screenshot taken from max iD zoom level: 24.

iD may be working at level 24, but as you can see looking up async requests in the browser, for the Geoportal WMTS it doesn't ever display tiles for levels bigger than 19. Requests for higher levels such as [this one](https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTOFOTOMAPA&STYLE=default&FORMAT=image/jpeg&tileMatrixSet=EPSG:3857&tileMatrix=EPSG:3857:23&tileRow=2763927&tileCol=4682510) for zoom 23 or [this one](https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTOFOTOMAPA&STYLE=default&FORMAT=image/jpeg&tileMatrixSet=EPSG:3857&tileMatrix=EPSG:3857:20&tileRow=345492&tileCol=585322) for zoom 20, which to my limited knowledge of WMTS look correct (matrix, row and col are according to bounds specified in _GetCapabilties_), return exactly nothing. I can imagine two different things causing this: either Geoportal doesn't actually have imagery for levels bigger than 19 and thus the response of _GetCapabilities_, and in consequence editor-layer-index is wrong, or there is something going on with the way the WMTS service is queried. For context, please note that iD (what about EveryDoor?) doesn't actually support the WMTS standard. The editor-layer-index [entry](https://raw.githubusercontent.com/osmlab/editor-layer-index/3c493f8c7ed65b046b76351013cb69d31711b4dc/sources/europe/pl/Geoportal2Orthophotomap(aerialimage)_WMTS.geojson) you linked uses the WMTS endpoint and represents it as if it was a TMS service and [that's how iD is using it](https://github.com/openstreetmap/iD/issues/8789#issuecomment-961714182). I'm not familiar with the intricacies of the standards and can't tell right now for sure if using the Geoportal WMTS as actually intended would change anything.

So as I understand, a client may simply stop making requests for tiles at zoom levels greater than a certain threshold and fall back to bluntly scaling the image obtained at the assumed or discovered max zoom level. @Zverik communicated above that he's not willing to this, but iD seems to be. Oddly enough, the effective maximum zoom level for this layer in iD seems to be (as stated above) 19, not level 23 which is documented in editor-layer-index and in _GetCapabilities_ for EPSG:3857 or level 16, which is indicated as the max in  _GetCapabilities_ for EPSG:4326 and EPSG:2180. Possibly, iD manages to fallback to scaling the highest-zoom tile available after discovering the requests to get tiles at higher zoom levels fail.

Another possible explanation of why iD doesn't suffer and EveryDoor does is the choice of projection. I already [asked before](https://github.com/Zverik/every_door/discussions/566) (without luck) for confirmation on EveryDoor's projection selection logic and since we're at it, I'd like to kindly ask @Zverik once more to have a look at this. I don't have means to test it in practice, but looking at the code it seems the app can use both EPSG:3857 and EPSG:4326. Is it possible that EveryDoor effectively uses the latter one, which according to _GetCapabilities_ doesn't go beyond zoom level 16?

**Comment by Zaczero** [comment]
> I can imagine two different things causing this: either Geoportal doesn't actually have imagery for levels bigger than 19 and thus the response of GetCapabilities

But because this also happens with Bing layer, I don't think this is a Geoportal issue.

**Comment by gdabski** [comment]
I can now confirm that the problem with Geoportal's standard resolution WMTS can be reproduced in QGIS. Requests for zoom levels bigger than 19 result in an empty response (no body).

**Comment by gdabski** [comment]
> But because this also happens with Bing layer, I don't think this is a Geoportal issue.

If my assumption was true and Geoportal didn't serve images beyond zoom level 19 how wouldn't it be a Geoportal issue?

**Comment by Zaczero** [comment]
> > But because this also happens with Bing layer, I don't think this is a Geoportal issue.
> 
> If my assumption was true and Geoportal didn't serve images beyond zoom level 19 how wouldn't it be a Geoportal issue?

But isn't that strange that this issue happens for Bing and Geoportal (didn't test any other layers)? Bing layer is so widely used, surely someone must have noticed something by now.

**Comment by gdabski** [comment]
It is a good remark that might help corroborating assumptions about the problem. I haven't myself checked Bing in any application yet though. Looking at the [editor-layer-index definition](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/world/Bing.geojson?short_path=6195018) now, we may have a hard time checking it out, because it's not a WMS or WMTS, but a type of its own. Looking at web requests made by iD, you can see that [the URL](https://ecn.t1.tiles.virtualearth.net/tiles/a1202131013103030301.jpeg?g=13716&pr=odbl&n=z) has even nothing to do with the Bing URL listed in ELI and doesn't indicate in an obvious way what zoom level is requested. In the end it might even be a different problem at the root cause.

And only on top of that you have the secondary question, could EveryDoor recognize problems with getting imagery and fall back to scaling whatever it has at hand. That's very likely possible as iD seems to be doing just that, but @Zverik indicated it's too much complexity to be worth it.

**Comment by Zaczero** [comment]
Thank you for your detailed explanation, it does make sense :-). For the sake of it, I tested all remaining layers available here in Poland and it looks like the esri layer has the same issue. It does not look like fixing each individual layer would be beneficial. Adding some sort of fallback will work the best here in terms of zero maintenance. Also, some regions may have higher zoom limits, some lower, depending on a layer which will be just a pain.

> That's very likely possible as iD seems to be doing just that, but @Zverik indicated it's too much complexity to be worth it.

This shouldn't be too hard: Check image size (or response code) and if needed scale back and update the current limit. Then keep that limit in memory until the application is restarted.

**Comment by mnalis** [comment]
- If Every Door supported scaling of imagery, that would also help solve this issue (via second bullet): https://github.com/Zverik/every_door/issues/589
