### ISSUE TITLE
Can't add WhatsApp number

### ISSUE THREAD

**Issue by Mannivu** [Zverik/every_door#670]
When trying to add a WhatsApp contact via the main window (so, without adding a specific tag in the advanced window) the editor does nothing: if I click on the tick, the number isn't added.

https://github.com/Zverik/every_door/assets/42747216/44386564-4ddc-474a-8816-45d63fc7048d

**Comment by mnalis** [comment]
I'm guessing it's because it is in invalid format; it should start with `+` sign, then country code etc. So if you type `+3403403403` instead, it should be accepted (it does for me).

What is interesting, if you try to enter invalid `phone` number, it will show yellow warnings, but would still allow to enter it in invalid format.

I would expect both `contact:whatsapp` and `phone` fields to use same validator...

**Comment by Zverik** [comment]
Fixed in 9308049.
