### ISSUE TITLE
Confirmation popup before upload

### ISSUE THREAD

**Issue by mfbehrens99** [Zverik/every_door#68]
I would also add I text input where to you can change the changeset comment

**Comment by Zverik** [comment]
I feel an urge to discard this issue, because having a static string for a comment "Surveyed POI in {geocoded area}" would be true and will fit 98% of all changesets made with the editor. The auto-generated comment we do now is even better.

Having to come up with a comment after an editing session, I feel, would be an additional unnecessary burden. Even if there is a default value or the field is optional, it is still one more thing to decide upon.

I don't know. Maybe later.

**Comment by mfbehrens99** [comment]
I would just put the auto-generated message in the box. If you don't care you can just press okay, if not you can change the comment

**Comment by mnalis** [comment]
I also often like giving changesets more meaningful names to me, so I can find them later. Having a thousand changesets named _"Created a shop"_ or something is not particularly useful (I can see I created the shop by looking at the tags, and I can see where it was by looking at the bbox)

I like the OsmAnd approach - fill in the default text, but allow user to change it before submitting if they like.

Another option might be to show dialog for changeset comment only when long-pressing the upload button, and regular press on upload button would just do quick upload immediately.  That would make it quick for regular users, but allow more advanced users to specify changeset comment.

**Comment by mnalis** [comment]
> Could you please write three different changeset comments that you might have entered in that dialog?

here are few inspired by my recent edit history:
- "remove duplicate nodes created by OsmAnd on failed upload" 
- "updating cycling infrastructure around lake Balaton from survey"
- "added <locatio> entrances from Bing imagery"
- "fix crossing location, it is actually now on the other side of the road, not as shown in HR_DOF2020"
- "update opening hours from web homepage as not signed at the entrance"

> What constitutes a useful changeset comment and for whom?

It is useful if it could be used by user to find changesets more easily, or to detect unintentional changes by 3rd parties, or to explain why something was done (the way it was done), what sources were (actually) used, etc.  All of that may help when original user or someone else later tries to make sense of suspicious changes or to try to understand what/why happened in that edit.

I find https://wiki.openstreetmap.org/wiki/Good_changeset_comments to be good overall explanation. 

It is of course best if comment is useful for everyone looking at it (but even a comment which is only useful for local community or even only for original mapper is better then comment which conveys no additional data to anyone).

**Comment by Zverik** [comment]
Thanks — but these are comments for a full-fledged editor. I meant, what could be good changeset comments in the context of Every Door, where edits are done in the field? Based on the editor name you already know where and why the edit happened, and current automatic comments indicate what. My question was, what is missing so the you need to type it out by hand?

**Comment by mnalis** [comment]
Actually I specifically chose those that do not rely on ways/areas (where most common would be "drawn missing buildings" and "aligned way according to satellite imagery XXXX") but only on POIs - and thus ones which one might (possibly) use in ED. 
To explain in more detail:

- _"remove duplicate nodes created by OsmAnd on failed upload"_
 This actually happened to me recently. OsmAnd failed and it resulted in duplicate upload, which I noticed because StreetComplete was asking me all questions in duplicate. I could've fixed that in ED, and then I would add a changeset comment like that to explain why I am deleting random POIs from the map when they are present there in reality.
 
-  _"updating cycling infrastructure around lake Balaton from survey"_
  Also happened. I biked around Balaton, and wish to enter/update missing POIs like bike repair stations, air pumps/compressors, rent-a-bikes, bike shops and similar. Yeah, 'Added shop(s)' etc. is not wrong, but is not as descriptive, and certainly wouldn't help me later when I wanted to find that changeset for whatever reason.

-  _"added entrances from Bing imagery"_
  ED allows showing different satellite/aerieal imagery. That imagery can be (and is) used to position and map things instead of walking to exact locations - especially in larger cities where GPS reception gets huge errors. And when using imagery to map things (like entrances or other POIs) it is quite useful later to know what was the source of the location, and what imagery exactly was used (esp. if there are questions or inconsistencies). Some of that information could be marked by using **other** **_changeset tags_** like [source=*](https://wiki.openstreetmap.org/wiki/Changeset#Tags_on_changesets), but that is even more problematic if user used multiple imagery (unless each imagery change forces current changes to be committed and closed - and even then, `source=*` by itself does not convey which part was used for what)
 
- _"fix crossing location, it is actually now on the other side of the road, not as shown in HR_DOF2020"_
  Also happened recently to me recently. I'm note sure if ED allows editing crosswalks (it happened before I've found out about ED), but if it does, on-the-ground would be the best place to fix that error (and note i changeset comment why it was done, so some armchair mapper wouldn't revert it according to obsolete satellite imagery later)
 
- _"update opening hours from web homepage as not signed at the entrance"_
  Same thing, useful on the ground. Sometimes opening hours, website, phone etc. are not signed on the entrance, but are on the website. I'll add POI and visible information from the ground, but I also want to add this important piece of information, which I copy from their website. It is useful to know the source of the data, so I put it in the changeset comment.


That being said, none of that is the end of the world. Nor it would be if ED for example put all the changes done in _whole month_ in _one huge changeset_ named "Some edits made with ED" instead of many smaller ones with more descriptive names.  It would be more annoying and less useful, but not the end of the world.

Still, it would be useful IMHO. But I do recognize that there are much more important issues that deserve to be fixed before (like https://github.com/Zverik/every_door/issues/255)

**Comment by Zverik** [comment]
Decided against this, but #394 helps with one practical case I did not envision.

Regarding this issue, I still think that date + area (ED splits changes into smaller boxes) + editor name + current comment do a better job at describing the changes than a person ever could.
