### ISSUE TITLE
display elevation field for playground=swing

### ISSUE THREAD

**Issue by teacupmaps** [Zverik/every_door#697]
swimgs are often so low that adults can't use them at all or it's uncomfortable. so if we have a way to measure it it's better to put it on the map.

**Comment by mnalis** [comment]
I agree! Is there documented tagging for how to map that leg space under a swing, though?
Because I'm not seeing it documented at the [wiki](https://wiki.openstreetmap.org/wiki/Key:playground#Swing_devices), or in use at the [taginfo](https://taginfo.openstreetmap.org/tags/playground=swing#combinations).

If it isn't being tagged yet, it should be [proposed](https://wiki.openstreetmap.org/wiki/Proposal_process) or at least discussed at a [OSM forum](https://community.openstreetmap.org/c/general/tagging/70/) first to decide how that should be tagged, before it can be implemented by editors like every_door (or more precisely [id-tagging-schema for playground=swing](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/playground/swing.json) which ever_door users).

(Please do add a link here if you open such discussion so interested parties can follow; thanks!)

**Comment by Zverik** [comment]
Yup, this should be implemented in the presets. Thanks Matija for explaining.
