### ISSUE TITLE
Where to add translation?

### ISSUE THREAD

**Issue by ERYpTION** [Zverik/every_door#707]
I have noticed a few untranslated items in the app but can't seem anywhere to translate them (to Danish). For example 'Mail drop box' looks like it was translated in the Transifex project for iD Editor at least two years ago. I can't find anywhere else to translate it?

**Comment by mnalis** [comment]
I see that Danish translation for `amenity/post_box` (`Mail drop box`) was published on [12 Jul 2022 in id-tagging-schema 3.4.0](https://github.com/openstreetmap/id-tagging-schema/blob/v3.4.0/dist/translations/da.json#L2908-L2910) so that one should indeed be in, as last everydoor release (4.1) happened on 6. Nov 2023, so I would expect it includes changes published before that.

And in EveryDoor 4.1 it indeed **seems to include that translation**, but I do see an interesting problem when it tries to use it:

When I manually switch language to Dansk in the app, try to add POI by searching for `Mail drop box`, I see 3 results: one is (correctly) translated to `Postkasse`, but there are two more instances that are not. 
All three tag **only** `amenity=post_box` (checked in raw tags editor), so those are not untranslated other sub-items. I'm puzzled why that happens; I would expect just one result...  

Also, when clicking on existing `amenity=post_box` (e.g. the one just created), it always shows English `Mail drop box` in that blue title, instead of Danish `Postkasse` (which I probably why @ERYpTION thought the translation didn't made it in). I'd guess this is connected with that duplication above.
 
![small_Screenshot_20240417_001435](https://github.com/Zverik/every_door/assets/156656/a1a38408-fb80-424e-9635-741ad115cfd8) ![small_Screenshot_20240417_002029](https://github.com/Zverik/every_door/assets/156656/91506869-74fc-4495-a0bf-da8e311ae71f)
