### ISSUE TITLE
Improvements and fixes to drawing mode

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#713]
* [x] отключить поворот карты в режиме рисования
* [x] отключить инерцию при смещении карты
* [x] обновлять effective location в режиме рисования (иначе не скачать новую область)
* [x] проверить, что слушаем геолокацию в режиме рисования
* [x] запретить отправку заметок без логина
* [x] когда есть плашка «данные устарели», нужно сместить панель выбора режима вверх.

**Comment by danieldegroot2** [comment]
Translated to English;
-  disable map rotation in drawing mode
-  disable slow response on map shift
-  update location in drawing mode (otherwise you won't be able to download a new area)
-  check that we listen to geolocation in drawing mode
-  disable sending notes without login
-  when there is a ‘data out of date’ bar, you should be able to move / have the mode selection panel up.
