### ISSUE TITLE
Quests like in Go map or StreetComplete

### ISSUE THREAD

**Issue by derkrasseleo** [Zverik/every_door#717]
Are there plans to add a "quests" mapping mode like in Go map or StreetComplete? I think this feature is one of the main reasons people are using these apps..

A few examples for quests: 

- Add opening times for businesses
- Add surface types
- Add street names for streets with no name

**Comment by derkrasseleo** [comment]
Maybe similar to #119

**Comment by Zverik** [comment]
Frankly, I'd keep projects separate. Every Door is for quick mapping of _everything_. Having quests would slow a user down. SC is indeed popular because quests make editing accessible and fun. But this editor is more like JOSM: no hand-holding, steeper learning curve, but nothing can stop you once you get going.
