### ISSUE TITLE
building:material vs building:facade:material

### ISSUE THREAD

**Issue by b-unicycling** [Zverik/every_door#725]
I noticed today that in the buildings mode, the preset asks for "facade material", but it is saved as `building:material`. That's not the same; often times, the facade will be brick, but the actual supporting walls are concrete blocks. For 3D rendering, it doesn't make a difference, but for sustainability and for the architectural history of the building, it does, for example. It should be saved as `building:facade:material`, in my opinion.

But thanks for putting `building:facade:material` into the drop-down options in the additional tags!

**Comment by mnalis** [comment]
> I noticed today that in the buildings mode, the preset asks for "facade material", but it is saved as `building:material`.

Yes. that is correct behavior. From the https://wiki.openstreetmap.org/wiki/Key:building:material wiki:

_"The key building:material=* is used to describe the outer surface material of building walls, also know as the facade or façade."_

And it has been saying mostly the same since it was documented in 2012, AFAICT.

Thus, `building:facade:material` is probably someone's mistaken [ATYL](https://wiki.openstreetmap.org/wiki/Any_tags_you_like) who didn't read the wiki, or didn't find that page, and didn't care enough to document the tag so other users could use it.   And since `building:facade:material` is being used 3 orders of magnitude less, and is not even documented, and provokes confusion, I would suggest that people avoid using it in any case.

So, `building:material` which is being offered (I guess via this [building iD preset](https://github.com/openstreetmap/id-tagging-schema/blob/6de5f5fde8cd6c48cd791bfdb7814650efdb45c2/data/presets/building.json#L14)) is (and has always been) about material of the facade, and **not** material of the load bearing structure (_"inside material of the walls"_).

So everything seems fine with current Every Door tagging and descriptions. If the visible facade is made of bricks, it should be (and is currently being) tagged with `building:material=brick`.

> the actual supporting walls are concrete blocks. For 3D rendering, it doesn't make a difference, but for sustainability and for the architectural history of the building, it does, for example

If there is interest in mapping structural load bearing materials of the buildings (instead of just facade material), one would need to invent some new tag to do it, something like `building:structure:material=*` or similar, but I guess that would not be hugely popular because it would fail [Verifiability](https://wiki.openstreetmap.org/wiki/Verifiability) principle (basically you'd need to be house builder who built some specific building to know what materials and support structures were used in each part of the building, as nobody else would _know_ the actual situation). Also, those would probably quite often differ per `building:part`... I don't think that people would use such tag much, really.

> But thanks for putting building:facade:material into the drop-down options in the additional tags!

My guess is that it  got included automatically as it is being used in the wild (as visible in [Taginfo](https://wiki.openstreetmap.org/wiki/Taginfo)). 

It is unfortunate that it got included as it is likely to confuse people (as shown by this issue) and perhaps even lead them to use incorrect tagging (e.g. just its existence might lead people to incorrectly use `building:material` for tagging load bearing structure material, instead of facade material).
