### ISSUE TITLE
[notes] Translate suggested values

### ISSUE THREAD

**Issue by matheusgomesms** [Zverik/every_door#732]
I also loved the new suggested values in the notes menu! Is it possible to have them translated in Weblate?

Or, should I dare (long shot here!), we could have our own set of them in the Settings menu (some mappers only map X or Y, so maybe this could be handy to them).

**Comment by Zverik** [comment]
I chose English for those values because it's an international language with a higher chance of being understood anywhere :)

Those get pushed down with notes present on the map, that appear at least twice. So you have to type a word twice, and then it's just taps. Maybe I would also add the last entered word, but idk for now.
