### ISSUE TITLE
FR: Update existing check_date or survey:date if already present

### ISSUE THREAD

**Issue by yrtimiD** [Zverik/every_door#751]
If an updated feature already has a survey:date tag - it's better to update it instead of adding extra check_date (quite popular StreetComplete uses survey:date)

**Comment by mnalis** [comment]
> quite popular StreetComplete uses `survey:date`

To add some context: while StreetComplete does indeed use `survey:date` ([among other tags](https://github.com/streetcomplete/StreetComplete/blob/v58.0/app/src/main/java/de/westnordost/streetcomplete/osm/ResurveyUtils.kt#L15-L21)) to determine if place should be resurveyed, when the mapper does confirm the place still exist, StreetComplete will remove `survey:date` and other similar tags and [replace them](https://github.com/streetcomplete/StreetComplete/blob/v58.0/app/src/main/java/de/westnordost/streetcomplete/osm/ResurveyUtils.kt#L95) with `check_date` (set to today, obviously).

There was also a discussion in https://github.com/streetcomplete/StreetComplete/issues/2592 few years ago about `survey:date` vs. `check_date` where the decision to use `check_date` was reaffirmed; so that thread might provide some background on the reasoning.

**Comment by Zverik** [comment]
Yeah, I assessed all the options when choosing the key, and `check_date` seems better fitting. Idk why people started adding `survey:date` in the first place.
