### ISSUE TITLE
Why is amenity=drinking_water exluded?

### ISSUE THREAD

**Issue by not-my-profile** [Zverik/every_door#761]
I'd like to edit drinking waters with the app but amenity=drinking_water cannot be downloaded. Why is it listed under wrongAmenities in good_tags.dart?

**Comment by mnalis** [comment]
> I'd like to edit drinking waters with the app but amenity=drinking_water cannot be downloaded

Could you explain in more detail exactly what do you click and what you expect to happen, and what happens instead?
You should be able to see/add/edit `amenity=drinking_water` normally in ***Micromapping mode*** (click on :evergreen_tree:  tree icon)

> Why is it listed under wrongAmenities in good_tags.dart?

AFAIK, because, even if under `amenity=*` key, it is **not** to be available under ***Amenity mode*** [^1] , but should instead be available under ***Micromapping mode***.


[^1]:  which [IIRC](https://github.com/streetcomplete/StreetComplete/issues/5152#issuecomment-1706595942) should be about _"venue manned by people or providing paid services. So, shops, churches, vending machines and parcel delivery machines, but not post boxes or garbage bins."_

**Comment by not-my-profile** [comment]
Ah sorry I didn't know that I had to click on the tree. Thanks!
