### ISSUE TITLE
No toilet option for restaurants

### ISSUE THREAD

**Issue by Zaczero** [Zverik/every_door#798]
I want to provide data about toilet availability in Restaurants, Gas stations, etc.

**Comment by Zverik** [comment]
Please tap on the "More fields" line and scroll down to this:

![ed-toilets-in-cafe](https://github.com/user-attachments/assets/caa8de2f-e6ec-40ef-af21-6b613c0c8fb0)

**Comment by Zaczero** [comment]
No such option:
- Burger Fast Food
- Gas Station
- Pizza Fast Food
- etc.

Is no support for it really not planned? Why?

**Comment by mnalis** [comment]
> No such option:
> *    Burger Fast Food

See [README / presets section](https://github.com/Zverik/every_door?tab=readme-ov-file#presets-and-translations), I think those are defined in id-tagging-schema repository, not here... 

e.g. compare https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/fast_food/burger.json to  https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/restaurant.json

As to why, I suggest that because often fast foods are takeaway-only, so don't really have toilets? But you can ask / request changes / submit PRs [there](https://github.com/openstreetmap/id-tagging-schema/) (feel free to link to this issue, so interested parties can follow)

> some gas stations offer toilets free of charge, some require a payment

BTW, that would be a good reason to map toilets as a **_separate_** `amenity=toilets` node (which you can do in EveryDoor), regardless whether you've added `toilets=*` property tag to that `amenity=fuel` or not. 
Doing so would also allow for adding other extra information like payment requirement, wheelchair suitability, payment methods, toilet types, availability of menstrual products, handwashing etc.

But yes, I agree you should ask for adding toilets on https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/fuel.json there.

**Comment by Zaczero** [comment]
Thank you for pointing me in the right direction :+1:
